// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

package com.trabalhoFinal.protos;

/**
 * Protobuf type {@code teste.Agenda}
 */
public final class Agenda extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:teste.Agenda)
    AgendaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Agenda.newBuilder() to construct.
  private Agenda(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Agenda() {
    contato_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Agenda();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Agenda(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              contato_ = new java.util.ArrayList<com.trabalhoFinal.protos.Contato>();
              mutable_bitField0_ |= 0x00000001;
            }
            contato_.add(
                input.readMessage(com.trabalhoFinal.protos.Contato.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        contato_ = java.util.Collections.unmodifiableList(contato_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Agenda_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Agenda_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trabalhoFinal.protos.Agenda.class, com.trabalhoFinal.protos.Agenda.Builder.class);
  }

  public static final int CONTATO_FIELD_NUMBER = 1;
  private java.util.List<com.trabalhoFinal.protos.Contato> contato_;
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.trabalhoFinal.protos.Contato> getContatoList() {
    return contato_;
  }
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.trabalhoFinal.protos.ContatoOrBuilder> 
      getContatoOrBuilderList() {
    return contato_;
  }
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  @java.lang.Override
  public int getContatoCount() {
    return contato_.size();
  }
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  @java.lang.Override
  public com.trabalhoFinal.protos.Contato getContato(int index) {
    return contato_.get(index);
  }
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  @java.lang.Override
  public com.trabalhoFinal.protos.ContatoOrBuilder getContatoOrBuilder(
      int index) {
    return contato_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < contato_.size(); i++) {
      output.writeMessage(1, contato_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < contato_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, contato_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trabalhoFinal.protos.Agenda)) {
      return super.equals(obj);
    }
    com.trabalhoFinal.protos.Agenda other = (com.trabalhoFinal.protos.Agenda) obj;

    if (!getContatoList()
        .equals(other.getContatoList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContatoCount() > 0) {
      hash = (37 * hash) + CONTATO_FIELD_NUMBER;
      hash = (53 * hash) + getContatoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trabalhoFinal.protos.Agenda parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Agenda parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trabalhoFinal.protos.Agenda parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trabalhoFinal.protos.Agenda parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trabalhoFinal.protos.Agenda prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teste.Agenda}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teste.Agenda)
      com.trabalhoFinal.protos.AgendaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Agenda_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Agenda_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trabalhoFinal.protos.Agenda.class, com.trabalhoFinal.protos.Agenda.Builder.class);
    }

    // Construct using com.trabalhoFinal.protos.Agenda.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getContatoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (contatoBuilder_ == null) {
        contato_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        contatoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Agenda_descriptor;
    }

    @java.lang.Override
    public com.trabalhoFinal.protos.Agenda getDefaultInstanceForType() {
      return com.trabalhoFinal.protos.Agenda.getDefaultInstance();
    }

    @java.lang.Override
    public com.trabalhoFinal.protos.Agenda build() {
      com.trabalhoFinal.protos.Agenda result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trabalhoFinal.protos.Agenda buildPartial() {
      com.trabalhoFinal.protos.Agenda result = new com.trabalhoFinal.protos.Agenda(this);
      int from_bitField0_ = bitField0_;
      if (contatoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          contato_ = java.util.Collections.unmodifiableList(contato_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.contato_ = contato_;
      } else {
        result.contato_ = contatoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trabalhoFinal.protos.Agenda) {
        return mergeFrom((com.trabalhoFinal.protos.Agenda)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trabalhoFinal.protos.Agenda other) {
      if (other == com.trabalhoFinal.protos.Agenda.getDefaultInstance()) return this;
      if (contatoBuilder_ == null) {
        if (!other.contato_.isEmpty()) {
          if (contato_.isEmpty()) {
            contato_ = other.contato_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContatoIsMutable();
            contato_.addAll(other.contato_);
          }
          onChanged();
        }
      } else {
        if (!other.contato_.isEmpty()) {
          if (contatoBuilder_.isEmpty()) {
            contatoBuilder_.dispose();
            contatoBuilder_ = null;
            contato_ = other.contato_;
            bitField0_ = (bitField0_ & ~0x00000001);
            contatoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContatoFieldBuilder() : null;
          } else {
            contatoBuilder_.addAllMessages(other.contato_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.trabalhoFinal.protos.Agenda parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.trabalhoFinal.protos.Agenda) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.trabalhoFinal.protos.Contato> contato_ =
      java.util.Collections.emptyList();
    private void ensureContatoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        contato_ = new java.util.ArrayList<com.trabalhoFinal.protos.Contato>(contato_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.trabalhoFinal.protos.Contato, com.trabalhoFinal.protos.Contato.Builder, com.trabalhoFinal.protos.ContatoOrBuilder> contatoBuilder_;

    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public java.util.List<com.trabalhoFinal.protos.Contato> getContatoList() {
      if (contatoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contato_);
      } else {
        return contatoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public int getContatoCount() {
      if (contatoBuilder_ == null) {
        return contato_.size();
      } else {
        return contatoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public com.trabalhoFinal.protos.Contato getContato(int index) {
      if (contatoBuilder_ == null) {
        return contato_.get(index);
      } else {
        return contatoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder setContato(
        int index, com.trabalhoFinal.protos.Contato value) {
      if (contatoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContatoIsMutable();
        contato_.set(index, value);
        onChanged();
      } else {
        contatoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder setContato(
        int index, com.trabalhoFinal.protos.Contato.Builder builderForValue) {
      if (contatoBuilder_ == null) {
        ensureContatoIsMutable();
        contato_.set(index, builderForValue.build());
        onChanged();
      } else {
        contatoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder addContato(com.trabalhoFinal.protos.Contato value) {
      if (contatoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContatoIsMutable();
        contato_.add(value);
        onChanged();
      } else {
        contatoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder addContato(
        int index, com.trabalhoFinal.protos.Contato value) {
      if (contatoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContatoIsMutable();
        contato_.add(index, value);
        onChanged();
      } else {
        contatoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder addContato(
        com.trabalhoFinal.protos.Contato.Builder builderForValue) {
      if (contatoBuilder_ == null) {
        ensureContatoIsMutable();
        contato_.add(builderForValue.build());
        onChanged();
      } else {
        contatoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder addContato(
        int index, com.trabalhoFinal.protos.Contato.Builder builderForValue) {
      if (contatoBuilder_ == null) {
        ensureContatoIsMutable();
        contato_.add(index, builderForValue.build());
        onChanged();
      } else {
        contatoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder addAllContato(
        java.lang.Iterable<? extends com.trabalhoFinal.protos.Contato> values) {
      if (contatoBuilder_ == null) {
        ensureContatoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contato_);
        onChanged();
      } else {
        contatoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder clearContato() {
      if (contatoBuilder_ == null) {
        contato_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        contatoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public Builder removeContato(int index) {
      if (contatoBuilder_ == null) {
        ensureContatoIsMutable();
        contato_.remove(index);
        onChanged();
      } else {
        contatoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public com.trabalhoFinal.protos.Contato.Builder getContatoBuilder(
        int index) {
      return getContatoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public com.trabalhoFinal.protos.ContatoOrBuilder getContatoOrBuilder(
        int index) {
      if (contatoBuilder_ == null) {
        return contato_.get(index);  } else {
        return contatoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public java.util.List<? extends com.trabalhoFinal.protos.ContatoOrBuilder> 
         getContatoOrBuilderList() {
      if (contatoBuilder_ != null) {
        return contatoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contato_);
      }
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public com.trabalhoFinal.protos.Contato.Builder addContatoBuilder() {
      return getContatoFieldBuilder().addBuilder(
          com.trabalhoFinal.protos.Contato.getDefaultInstance());
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public com.trabalhoFinal.protos.Contato.Builder addContatoBuilder(
        int index) {
      return getContatoFieldBuilder().addBuilder(
          index, com.trabalhoFinal.protos.Contato.getDefaultInstance());
    }
    /**
     * <code>repeated .teste.Contato contato = 1;</code>
     */
    public java.util.List<com.trabalhoFinal.protos.Contato.Builder> 
         getContatoBuilderList() {
      return getContatoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.trabalhoFinal.protos.Contato, com.trabalhoFinal.protos.Contato.Builder, com.trabalhoFinal.protos.ContatoOrBuilder> 
        getContatoFieldBuilder() {
      if (contatoBuilder_ == null) {
        contatoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.trabalhoFinal.protos.Contato, com.trabalhoFinal.protos.Contato.Builder, com.trabalhoFinal.protos.ContatoOrBuilder>(
                contato_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        contato_ = null;
      }
      return contatoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:teste.Agenda)
  }

  // @@protoc_insertion_point(class_scope:teste.Agenda)
  private static final com.trabalhoFinal.protos.Agenda DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trabalhoFinal.protos.Agenda();
  }

  public static com.trabalhoFinal.protos.Agenda getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Agenda>
      PARSER = new com.google.protobuf.AbstractParser<Agenda>() {
    @java.lang.Override
    public Agenda parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Agenda(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Agenda> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Agenda> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trabalhoFinal.protos.Agenda getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

