// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

package com.trabalhoFinal.protos;

public interface AgendaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teste.Agenda)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  java.util.List<com.trabalhoFinal.protos.Contato> 
      getContatoList();
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  com.trabalhoFinal.protos.Contato getContato(int index);
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  int getContatoCount();
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  java.util.List<? extends com.trabalhoFinal.protos.ContatoOrBuilder> 
      getContatoOrBuilderList();
  /**
   * <code>repeated .teste.Contato contato = 1;</code>
   */
  com.trabalhoFinal.protos.ContatoOrBuilder getContatoOrBuilder(
      int index);
}
