// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

package com.trabalhoFinal.protos;

public final class AgendaProtos {
  private AgendaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teste_Contato_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teste_Contato_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teste_Contato_Email_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teste_Contato_Email_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teste_Contato_Telefone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teste_Contato_Telefone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teste_Contato_Endereco_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teste_Contato_Endereco_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teste_Agenda_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teste_Agenda_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teste_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teste_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014agenda.proto\022\005teste\"\244\003\n\007Contato\022\014\n\004nom" +
      "e\030\001 \001(\t\022$\n\006emails\030\002 \003(\0132\024.teste.Contato." +
      "Email\022)\n\010telefone\030\003 \003(\0132\027.teste.Contato." +
      "Telefone\022)\n\010endereco\030\004 \003(\0132\027.teste.Conta" +
      "to.Endereco\032%\n\005Email\022\022\n\005email\030\001 \001(\tH\000\210\001\001" +
      "B\010\n\006_email\032_\n\010Telefone\022\025\n\010telefone\030\001 \001(\t" +
      "H\000\210\001\001\022&\n\004type\030\002 \001(\0162\023.teste.Contato.Type" +
      "H\001\210\001\001B\013\n\t_telefoneB\007\n\005_type\032_\n\010Endereco\022" +
      "\025\n\010endereco\030\001 \001(\tH\000\210\001\001\022&\n\004type\030\002 \001(\0162\023.t" +
      "este.Contato.TypeH\001\210\001\001B\013\n\t_enderecoB\007\n\005_" +
      "type\"&\n\004Type\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WO" +
      "RK\020\002\")\n\006Agenda\022\037\n\007contato\030\001 \003(\0132\016.teste." +
      "Contato\"Y\n\007Message\022\014\n\004type\030\001 \001(\005\022\n\n\002id\030\002" +
      " \001(\005\022\024\n\014objReference\030\003 \001(\t\022\020\n\010methodId\030\004" +
      " \001(\t\022\014\n\004args\030\005 \001(\014B*\n\030com.trabalhoFinal." +
      "protosB\014AgendaProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_teste_Contato_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_teste_Contato_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teste_Contato_descriptor,
        new java.lang.String[] { "Nome", "Emails", "Telefone", "Endereco", });
    internal_static_teste_Contato_Email_descriptor =
      internal_static_teste_Contato_descriptor.getNestedTypes().get(0);
    internal_static_teste_Contato_Email_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teste_Contato_Email_descriptor,
        new java.lang.String[] { "Email", "Email", });
    internal_static_teste_Contato_Telefone_descriptor =
      internal_static_teste_Contato_descriptor.getNestedTypes().get(1);
    internal_static_teste_Contato_Telefone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teste_Contato_Telefone_descriptor,
        new java.lang.String[] { "Telefone", "Type", "Telefone", "Type", });
    internal_static_teste_Contato_Endereco_descriptor =
      internal_static_teste_Contato_descriptor.getNestedTypes().get(2);
    internal_static_teste_Contato_Endereco_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teste_Contato_Endereco_descriptor,
        new java.lang.String[] { "Endereco", "Type", "Endereco", "Type", });
    internal_static_teste_Agenda_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_teste_Agenda_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teste_Agenda_descriptor,
        new java.lang.String[] { "Contato", });
    internal_static_teste_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_teste_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teste_Message_descriptor,
        new java.lang.String[] { "Type", "Id", "ObjReference", "MethodId", "Args", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
