// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

package com.trabalhoFinal.protos;

public interface ContatoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teste.Contato)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nome = 1;</code>
   * @return The nome.
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 1;</code>
   * @return The bytes for nome.
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>repeated .teste.Contato.Email emails = 2;</code>
   */
  java.util.List<com.trabalhoFinal.protos.Contato.Email> 
      getEmailsList();
  /**
   * <code>repeated .teste.Contato.Email emails = 2;</code>
   */
  com.trabalhoFinal.protos.Contato.Email getEmails(int index);
  /**
   * <code>repeated .teste.Contato.Email emails = 2;</code>
   */
  int getEmailsCount();
  /**
   * <code>repeated .teste.Contato.Email emails = 2;</code>
   */
  java.util.List<? extends com.trabalhoFinal.protos.Contato.EmailOrBuilder> 
      getEmailsOrBuilderList();
  /**
   * <code>repeated .teste.Contato.Email emails = 2;</code>
   */
  com.trabalhoFinal.protos.Contato.EmailOrBuilder getEmailsOrBuilder(
      int index);

  /**
   * <code>repeated .teste.Contato.Telefone telefone = 3;</code>
   */
  java.util.List<com.trabalhoFinal.protos.Contato.Telefone> 
      getTelefoneList();
  /**
   * <code>repeated .teste.Contato.Telefone telefone = 3;</code>
   */
  com.trabalhoFinal.protos.Contato.Telefone getTelefone(int index);
  /**
   * <code>repeated .teste.Contato.Telefone telefone = 3;</code>
   */
  int getTelefoneCount();
  /**
   * <code>repeated .teste.Contato.Telefone telefone = 3;</code>
   */
  java.util.List<? extends com.trabalhoFinal.protos.Contato.TelefoneOrBuilder> 
      getTelefoneOrBuilderList();
  /**
   * <code>repeated .teste.Contato.Telefone telefone = 3;</code>
   */
  com.trabalhoFinal.protos.Contato.TelefoneOrBuilder getTelefoneOrBuilder(
      int index);

  /**
   * <pre>
   *google.protobuf.Timestamp last_updated = 5;
   * </pre>
   *
   * <code>repeated .teste.Contato.Endereco endereco = 4;</code>
   */
  java.util.List<com.trabalhoFinal.protos.Contato.Endereco> 
      getEnderecoList();
  /**
   * <pre>
   *google.protobuf.Timestamp last_updated = 5;
   * </pre>
   *
   * <code>repeated .teste.Contato.Endereco endereco = 4;</code>
   */
  com.trabalhoFinal.protos.Contato.Endereco getEndereco(int index);
  /**
   * <pre>
   *google.protobuf.Timestamp last_updated = 5;
   * </pre>
   *
   * <code>repeated .teste.Contato.Endereco endereco = 4;</code>
   */
  int getEnderecoCount();
  /**
   * <pre>
   *google.protobuf.Timestamp last_updated = 5;
   * </pre>
   *
   * <code>repeated .teste.Contato.Endereco endereco = 4;</code>
   */
  java.util.List<? extends com.trabalhoFinal.protos.Contato.EnderecoOrBuilder> 
      getEnderecoOrBuilderList();
  /**
   * <pre>
   *google.protobuf.Timestamp last_updated = 5;
   * </pre>
   *
   * <code>repeated .teste.Contato.Endereco endereco = 4;</code>
   */
  com.trabalhoFinal.protos.Contato.EnderecoOrBuilder getEnderecoOrBuilder(
      int index);
}
