// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

package com.trabalhoFinal.protos;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teste.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string objReference = 3;</code>
   * @return The objReference.
   */
  java.lang.String getObjReference();
  /**
   * <code>string objReference = 3;</code>
   * @return The bytes for objReference.
   */
  com.google.protobuf.ByteString
      getObjReferenceBytes();

  /**
   * <code>string methodId = 4;</code>
   * @return The methodId.
   */
  java.lang.String getMethodId();
  /**
   * <code>string methodId = 4;</code>
   * @return The bytes for methodId.
   */
  com.google.protobuf.ByteString
      getMethodIdBytes();

  /**
   * <code>bytes args = 5;</code>
   * @return The args.
   */
  com.google.protobuf.ByteString getArgs();
}
