// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

package com.trabalhoFinal.protos;

/**
 * Protobuf type {@code teste.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:teste.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    objReference_ = "";
    methodId_ = "";
    args_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            type_ = input.readInt32();
            break;
          }
          case 16: {

            id_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            objReference_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            methodId_ = s;
            break;
          }
          case 42: {

            args_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trabalhoFinal.protos.Message.class, com.trabalhoFinal.protos.Message.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int OBJREFERENCE_FIELD_NUMBER = 3;
  private volatile java.lang.Object objReference_;
  /**
   * <code>string objReference = 3;</code>
   * @return The objReference.
   */
  @java.lang.Override
  public java.lang.String getObjReference() {
    java.lang.Object ref = objReference_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objReference_ = s;
      return s;
    }
  }
  /**
   * <code>string objReference = 3;</code>
   * @return The bytes for objReference.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjReferenceBytes() {
    java.lang.Object ref = objReference_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objReference_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODID_FIELD_NUMBER = 4;
  private volatile java.lang.Object methodId_;
  /**
   * <code>string methodId = 4;</code>
   * @return The methodId.
   */
  @java.lang.Override
  public java.lang.String getMethodId() {
    java.lang.Object ref = methodId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodId_ = s;
      return s;
    }
  }
  /**
   * <code>string methodId = 4;</code>
   * @return The bytes for methodId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodIdBytes() {
    java.lang.Object ref = methodId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARGS_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString args_;
  /**
   * <code>bytes args = 5;</code>
   * @return The args.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getArgs() {
    return args_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeInt32(1, type_);
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objReference_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, objReference_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, methodId_);
    }
    if (!args_.isEmpty()) {
      output.writeBytes(5, args_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objReference_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, objReference_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, methodId_);
    }
    if (!args_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, args_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trabalhoFinal.protos.Message)) {
      return super.equals(obj);
    }
    com.trabalhoFinal.protos.Message other = (com.trabalhoFinal.protos.Message) obj;

    if (getType()
        != other.getType()) return false;
    if (getId()
        != other.getId()) return false;
    if (!getObjReference()
        .equals(other.getObjReference())) return false;
    if (!getMethodId()
        .equals(other.getMethodId())) return false;
    if (!getArgs()
        .equals(other.getArgs())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + OBJREFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getObjReference().hashCode();
    hash = (37 * hash) + METHODID_FIELD_NUMBER;
    hash = (53 * hash) + getMethodId().hashCode();
    hash = (37 * hash) + ARGS_FIELD_NUMBER;
    hash = (53 * hash) + getArgs().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trabalhoFinal.protos.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trabalhoFinal.protos.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trabalhoFinal.protos.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trabalhoFinal.protos.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code teste.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:teste.Message)
      com.trabalhoFinal.protos.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trabalhoFinal.protos.Message.class, com.trabalhoFinal.protos.Message.Builder.class);
    }

    // Construct using com.trabalhoFinal.protos.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      id_ = 0;

      objReference_ = "";

      methodId_ = "";

      args_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trabalhoFinal.protos.AgendaProtos.internal_static_teste_Message_descriptor;
    }

    @java.lang.Override
    public com.trabalhoFinal.protos.Message getDefaultInstanceForType() {
      return com.trabalhoFinal.protos.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.trabalhoFinal.protos.Message build() {
      com.trabalhoFinal.protos.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trabalhoFinal.protos.Message buildPartial() {
      com.trabalhoFinal.protos.Message result = new com.trabalhoFinal.protos.Message(this);
      result.type_ = type_;
      result.id_ = id_;
      result.objReference_ = objReference_;
      result.methodId_ = methodId_;
      result.args_ = args_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trabalhoFinal.protos.Message) {
        return mergeFrom((com.trabalhoFinal.protos.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trabalhoFinal.protos.Message other) {
      if (other == com.trabalhoFinal.protos.Message.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getObjReference().isEmpty()) {
        objReference_ = other.objReference_;
        onChanged();
      }
      if (!other.getMethodId().isEmpty()) {
        methodId_ = other.methodId_;
        onChanged();
      }
      if (other.getArgs() != com.google.protobuf.ByteString.EMPTY) {
        setArgs(other.getArgs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.trabalhoFinal.protos.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.trabalhoFinal.protos.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ ;
    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object objReference_ = "";
    /**
     * <code>string objReference = 3;</code>
     * @return The objReference.
     */
    public java.lang.String getObjReference() {
      java.lang.Object ref = objReference_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objReference_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string objReference = 3;</code>
     * @return The bytes for objReference.
     */
    public com.google.protobuf.ByteString
        getObjReferenceBytes() {
      java.lang.Object ref = objReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string objReference = 3;</code>
     * @param value The objReference to set.
     * @return This builder for chaining.
     */
    public Builder setObjReference(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objReference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string objReference = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjReference() {
      
      objReference_ = getDefaultInstance().getObjReference();
      onChanged();
      return this;
    }
    /**
     * <code>string objReference = 3;</code>
     * @param value The bytes for objReference to set.
     * @return This builder for chaining.
     */
    public Builder setObjReferenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objReference_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object methodId_ = "";
    /**
     * <code>string methodId = 4;</code>
     * @return The methodId.
     */
    public java.lang.String getMethodId() {
      java.lang.Object ref = methodId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string methodId = 4;</code>
     * @return The bytes for methodId.
     */
    public com.google.protobuf.ByteString
        getMethodIdBytes() {
      java.lang.Object ref = methodId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string methodId = 4;</code>
     * @param value The methodId to set.
     * @return This builder for chaining.
     */
    public Builder setMethodId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      methodId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string methodId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodId() {
      
      methodId_ = getDefaultInstance().getMethodId();
      onChanged();
      return this;
    }
    /**
     * <code>string methodId = 4;</code>
     * @param value The bytes for methodId to set.
     * @return This builder for chaining.
     */
    public Builder setMethodIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      methodId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString args_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes args = 5;</code>
     * @return The args.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getArgs() {
      return args_;
    }
    /**
     * <code>bytes args = 5;</code>
     * @param value The args to set.
     * @return This builder for chaining.
     */
    public Builder setArgs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      args_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes args = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearArgs() {
      
      args_ = getDefaultInstance().getArgs();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:teste.Message)
  }

  // @@protoc_insertion_point(class_scope:teste.Message)
  private static final com.trabalhoFinal.protos.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trabalhoFinal.protos.Message();
  }

  public static com.trabalhoFinal.protos.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trabalhoFinal.protos.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

